# Generated by Django 2.1.2 on 2018-10-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buslevel',
            fields=[
                ('buslevelid', models.AutoField(db_column='BusLevelID', primary_key=True, serialize=False)),
                ('busleveldesc', models.CharField(db_column='BusLevelDesc', max_length=45)),
            ],
            options={
                'db_table': 'buslevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Busstatus',
            fields=[
                ('busstatusid', models.AutoField(db_column='BusStatusID', primary_key=True, serialize=False)),
                ('busstatusdesc', models.CharField(db_column='BusStatusDesc', max_length=45)),
            ],
            options={
                'db_table': 'busstatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Civilstat',
            fields=[
                ('civilstatid', models.AutoField(db_column='CivilStatID', primary_key=True, serialize=False)),
                ('civilstatdesc', models.CharField(db_column='CivilStatDesc', max_length=45)),
            ],
            options={
                'db_table': 'civilstat',
                'managed': False,
            },
        ),
    ]
