# Generated by Django 2.1.2 on 2018-10-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_buslevel_busstatus_civilstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clienttype',
            fields=[
                ('clienttypeid', models.AutoField(db_column='ClientTypeID', primary_key=True, serialize=False)),
                ('clienttypedesc', models.CharField(db_column='ClientTypeDesc', max_length=45)),
                ('clienttypeistaxable', models.PositiveIntegerField(db_column='ClientTypeIsTaxable')),
            ],
            options={
                'db_table': 'clienttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Closedreason',
            fields=[
                ('closedreasonid', models.AutoField(db_column='ClosedReasonID', primary_key=True, serialize=False)),
                ('closedreasondesc', models.CharField(db_column='ClosedReasonDesc', max_length=45)),
            ],
            options={
                'db_table': 'closedreason',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dosritag',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('desc1', models.CharField(db_column='DESC1', max_length=45)),
                ('desc2', models.CharField(blank=True, db_column='DESC2', max_length=200, null=True)),
            ],
            options={
                'db_table': 'dosritag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educattained',
            fields=[
                ('educattainedid', models.AutoField(db_column='EducAttainedID', primary_key=True, serialize=False)),
                ('educattaineddesc', models.CharField(db_column='EducAttainedDesc', max_length=45)),
            ],
            options={
                'db_table': 'educattained',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empcode',
            fields=[
                ('empcodeid', models.PositiveIntegerField(db_column='EmpCodeID', primary_key=True, serialize=False)),
                ('empcodedesc', models.CharField(db_column='EmpCodeDesc', max_length=50)),
            ],
            options={
                'db_table': 'empcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('genderid', models.AutoField(db_column='GenderID', primary_key=True, serialize=False)),
                ('genderdesc', models.CharField(db_column='GenderDesc', max_length=45)),
            ],
            options={
                'db_table': 'gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('geoid', models.PositiveSmallIntegerField(db_column='GeoID')),
                ('geodesc', models.CharField(db_column='GeoDesc', max_length=45)),
                ('geobr_code', models.ForeignKey(db_column='GeoBR_CODE', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='client.Branches')),
                ('geoupddatetime', models.DateTimeField(blank=True, db_column='GeoUpdDateTime', null=True)),
                ('geocollchartid', models.PositiveIntegerField(blank=True, db_column='GeoCollChartID', null=True)),
            ],
            options={
                'db_table': 'geo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indu',
            fields=[
                ('induid', models.PositiveSmallIntegerField(db_column='InduID', primary_key=True, serialize=False)),
                ('indudesc', models.CharField(blank=True, db_column='InduDesc', max_length=255, null=True)),
                ('ciccode', models.CharField(blank=True, db_column='CICCode', max_length=10, null=True)),
            ],
            options={
                'db_table': 'indu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industryid', models.PositiveSmallIntegerField(db_column='IndustryID', primary_key=True, serialize=False)),
                ('industrydesc', models.CharField(blank=True, db_column='IndustryDesc', max_length=255, null=True)),
                ('indugrp', models.CharField(blank=True, db_column='InduGrp', max_length=10, null=True)),
                ('ciccode', models.CharField(blank=True, db_column='CICCode', max_length=10, null=True)),
            ],
            options={
                'db_table': 'industry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jnttype',
            fields=[
                ('jnttypeid', models.AutoField(db_column='JntTypeID', primary_key=True, serialize=False)),
                ('jnttypedesc', models.CharField(db_column='JntTypeDesc', max_length=45)),
            ],
            options={
                'db_table': 'jnttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mailingaddress',
            fields=[
                ('mailingaddressid', models.AutoField(db_column='MailingAddressID', primary_key=True, serialize=False)),
                ('mailingaddressdesc', models.CharField(db_column='MailingAddressDesc', max_length=45)),
            ],
            options={
                'db_table': 'mailingaddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occu',
            fields=[
                ('occuid', models.PositiveSmallIntegerField(db_column='OccuID', primary_key=True, serialize=False)),
                ('occudesc', models.CharField(db_column='OccuDesc', max_length=100)),
            ],
            options={
                'db_table': 'occu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingid', models.AutoField(db_column='RatingID', primary_key=True, serialize=False)),
                ('ratingdesc', models.CharField(db_column='RatingDesc', max_length=100)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restype',
            fields=[
                ('restypeid', models.AutoField(db_column='ResTypeID', primary_key=True, serialize=False)),
                ('restypedesc', models.CharField(db_column='ResTypeDesc', max_length=45)),
            ],
            options={
                'db_table': 'restype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sectorid', models.PositiveIntegerField(db_column='SectorID', primary_key=True, serialize=False)),
                ('sectordesc', models.CharField(db_column='SectorDesc', max_length=45)),
            ],
            options={
                'db_table': 'sector',
                'managed': False,
            },
        ),
    ]
