# Generated by Django 2.1.2 on 2018-10-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clienttype_closedreason_dosritag_educattained_empcode_gender_geo_indu_industry_jnttype_mailingaddres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptid', models.AutoField(db_column='DeptID', primary_key=True, serialize=False)),
                ('deptdesc', models.CharField(db_column='DeptDesc', max_length=30)),
            ],
            options={
                'db_table': 'dept',
                'managed': False,
            },
        ),
    ]
