# Generated by Django 2.1.2 on 2018-10-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restrik',
            fields=[
                ('restrikid', models.PositiveIntegerField(db_column='RestrikID', primary_key=True, serialize=False)),
                ('restrikdesc', models.CharField(db_column='RestrikDesc', max_length=200)),
            ],
            options={
                'db_table': 'restrik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolid', models.PositiveSmallIntegerField(db_column='SchoolID', primary_key=True, serialize=False)),
                ('schooldesc', models.CharField(db_column='SchoolDesc', max_length=200)),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionid', models.PositiveSmallIntegerField(db_column='SectionID', primary_key=True, serialize=False)),
                ('sectiondesc', models.CharField(db_column='SectionDesc', max_length=200)),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
    ]
