# Generated by Django 2.1.2 on 2018-10-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_restrik_school_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.PositiveIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('desc1', models.CharField(blank=True, db_column='DESC1', max_length=200, null=True)),
                ('clientid', models.PositiveIntegerField(blank=True, db_column='CLIENTID', null=True)),
            ],
            options={
                'db_table': 'grouping',
                'managed': False,
            },
        ),
    ]
